name: CI/CD

on:
  push:
    #    paths:
    #      - "backend/**"
    branches: [ "main" ]

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Make yml
        run: |
          cd ./src/main/resources
          touch ./aws.yml
          echo "${{ secrets.BACKEND_YML }}" > ./aws.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -r ./BE-$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./BE-$GITHUB_SHA.zip s3://funit-ci-cd/BE-$GITHUB_SHA.zip
      - name: Code Deploy
        run: aws deploy create-deployment --application-name spring-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name spring-deploy-group --s3-location bucket=funit-ci-cd,bundleType=zip,key=BE-$GITHUB_SHA.zip

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: npm install
        run: npm install

      - name: Build project
        run: npm run build

      - name: cp appspec.yml
        run: cp appspec.yml ./dist/appspec.yml

      - name: Make zip file
        run: zip -r ./FE-$GITHUB_SHA.zip ./dist/*
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./FE-$GITHUB_SHA.zip s3://funit-ci-cd/FE-$GITHUB_SHA.zip
      - name: Code Deploy
        run: aws deploy create-deployment --application-name react-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name react-deploy-group --s3-location bucket=funit-ci-cd,bundleType=zip,key=FE-$GITHUB_SHA.zip

