name: CI/CD Frontend

on:
  push:
    #    paths:
    #      - "frontend/**"
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v3
        
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip ./dist/*
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://funit-ci-cd/$GITHUB_SHA.zip
      - name: Code Deploy
        run: aws deploy create-deployment --application-name react-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name react-deploy-group --s3-location bucket=funit-ci-cd,bundleType=zip,key=$GITHUB_SHA.zip
      
      
